### ISSUE TITLE
Orbital doesn't clip long window titles

### ISSUE THREAD

**Issue by xTibor** [redox-os/orbital#10]
It causes glitch traces when windows with long titles are moved across the screen. Tested with the latest 0.1.0 ISO.

Reproduction: https://gfycat.com/ComplexSizzlingJapanesebeetle

**Comment by jackpot51** [comment]
Thanks! I will fix this shortly

**Comment by xTibor** [comment]
Thanks. I must admit I played more with it than I should have. :)

**Comment by jackpot51** [comment]
This is fixed in master
