### ISSUE TITLE
Introducing a new `titleless` window property

### ISSUE THREAD

**Issue by xTibor** [redox-os/orbital#20]
The titlebar visibility currently controlled by the the window's title string, if it's empty the titlebar is hidden. This is problematic for two reasons:

* Windows without titlebars cannot have titles. As a result of this all the titlebarless apps (`launcher`, `background`, `login`, etc.) shows up as unnamed in the Alt+Tab switcher: https://i.imgur.com/sb5jAOw.png
* Windows with titlebars cannot have empty titles.

Could this be solved by introducing a new `titleless` window property to control the titlebar visibility?

**Comment by jackpot51** [comment]
Working on this.

**Comment by jackpot51** [comment]
This will be "borderless", and will be passed as a "b" from orbclient

**Comment by jackpot51** [comment]
Oops, b is already taken

**Comment by xTibor** [comment]
Before I forget, `minifb` needs to be updated after this. It already uses this feature with the old API.

**Comment by jackpot51** [comment]
I got it into orbclient 0.3.14 if you wnat to take a look. `WindowFlag::Borderless`

**Comment by xTibor** [comment]
Ok, I'll update it tomorrow.
