### ISSUE TITLE
Dragging borderless windows

### ISSUE THREAD

**Issue by xTibor** [redox-os/orbital#7]
The window manager can be tricked into dragging borderless windows, for example the taskbar.

Here's some ways I found to do it:
* Borderless windows can be dragged by the top-left pixel of the screen.
* ~~Pressing <kbd>Esc</kbd> to close any window while dragging it doesn't cancel the dragging event thus the next window gets immediately dragged. That next window can be the taskbar too.~~
* ~~This one is similar to the previous one. Pressing <kbd>Win</kbd>+<kbd>Tab</kbd> while dragging a window switches to the next window without canceling the drag event.~~

**Comment by jackpot51** [comment]
Thanks for the observations!

**Comment by xTibor** [comment]
It's partially fixed by 0.1.1.

**Comment by xTibor** [comment]
The issue is fixed, cannot be reproduced anymore. (0.1.2)

**Comment by jackpot51** [comment]
Thanks for testing! I am making Rect's at -1,-1 now instead of 0,0 to indicate empty titles
